### ISSUE TITLE
Keine Anzeige im Firefox Developer?

### ISSUE THREAD

**Issue by Geri2017** [yakamara/yduplicate#2]
Firefox Developer 70.0b13 (64-Bit) und im FF Quantum 69.0.3 (64-Bit)
MAC OS 11

![Bildschirmfoto 2019-10-11 um 12 23 55](https://user-images.githubusercontent.com/45007596/66644775-12cd5300-ec22-11e9-988f-a9b7dc2d6634.png)

**Comment by tbaddade** [comment]
Probier noch mal. Falls deine Tabelle sehr viele Felder hat, dann am besten im Setup nur einzelnen  Felder hinterlegen.
